[package]
name = "schema_registry_converter"
version = "0.1.0"
authors = ["Gerard Klijs <g.klijs@gmail.com>"]
description = "Encode/decode data from/to kafka using the Confluent Schema Registry"
homepage = "https://github.com/gklijs/schema_registry_converter"
readme = "README.md"
keywords = ["kafka", "encode", "decode", "schema", "avro"]
categories = ["encoding", "parsing"]
license = "MIT/Apache-2.0"
repository = "https://github.com/gklijs/schema_registry_converter"

[dependencies.avro-rs]
version = ">= 0.6"

[dependencies.byteorder]
version = ">= 1.0"

[dependencies.curl]
version = ">= 0.4"

[dependencies.serde_json]
version = ">=0.8.0, <2.0"

[dev-dependencies]
mockito = "0.12.0"
rdkafka = "0.17.0"
rdkafka-sys = "0.11.4"

[badges.appveyor]
branch = "master"
repository = "gklijs/schema_registry_converter"
service = "github"

[badges.travis-ci]
branch = "master"
repository = "gklijs/schema_registry_converter"