[package]
name = "schema_registry_converter"
version = "0.1.0"
authors = ["Gerard Klijs <g.klijs@gmail.com>"]
description = "Encode/decode data from/to kafka using the Confluent Schema Registry"
readme = "README.md"
keywords = ["kafka", "encode", "decode", "schema", "avro"]
categories = ["data"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/gklijs/schema_registry_converter"

[dependencies.avro-rs]
version = ">= 0.6"

[dependencies.byteorder]
version = ">= 1.0"

[dependencies.curl]
version = ">= 0.4"

[dependencies.rdkafka]
version = ">= 0.17"

[dependencies.serde_json]
version = ">=0.8.0, <2.0"