[package]
name = "schema-registry-custom-client"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
schema-registry-converter = { path = "../../schema-registry-converter", features = ["avro"] }
